In [1]:
import plotly.graph_objects as go
import numpy as np
import pandas as pd
import plotly.offline as pyo
import plotly.express as px

In [3]:
match = pd.read_csv('/Dataset/matches.csv')
delivery = pd.read_csv('/Dataset/deliveries.csv')

delivery = delivery.merge(match,left_on='match_id',right_on='id')
match.head()

FileNotFoundError: [Errno 2] No such file or directory: '/Dataset/matches.csv'

In [8]:
top_50 = list(delivery['batsman'].value_counts().iloc[:50].index)
temp_df = delivery[delivery['batsman'].isin(top_50)]
batsman_runs = temp_df.groupby('batsman')['batsman_runs'].sum()
batsman_balls = temp_df.groupby('batsman')['batsman_runs'].count()



sr = 100*batsman_runs/batsman_balls
sr = sr.reset_index()
sr.rename(columns={'batsman_runs':'Strikerate'},inplace=True)

In [9]:
temp_df = delivery[(delivery['batsman'].isin(top_50)) & ((delivery['player_dismissed'] == delivery['batsman']) | (delivery['player_dismissed'] == delivery['non_striker']))]
batsman_out = temp_df.groupby('batsman')['player_dismissed'].count().sort_values(ascending=False)
avg = (batsman_runs/batsman_out).reset_index()

avg = avg.merge(sr,on='batsman')
avg.rename(columns={0:'Average','batsman_runs':'Strikerate'},inplace=True)
avg.head()

          batsman    Average  Strikerate
0  AB de Villiers  41.011765  145.129059
1    AC Gilchrist  27.223684  133.054662
2        AJ Finch  27.655172  126.299213
3       AM Rahane  33.593407  117.486549
4       AT Rayudu  27.454545  123.014257

In [12]:
#plot a scatter plot

trace1 = go.Scatter(x=avg['Average'],y=avg['Strikerate'],mode='markers',text=avg['batsman'],marker={'color':'black','size':15})
data = [trace1]
layout = go.Layout(title='Average Vs Strikerate',xaxis={'title':'Batsman Average'},yaxis={'title':'Batsman Strikerate'})
fig = go.Figure(data=data,layout=layout)
# pyo.plot(fig)
fig.show()

In [29]:
#line chart
#year by year virat's performance

temp_df = delivery[delivery['batsman'] == 'V Kohli']
teams_runs = temp_df.groupby('season')['batsman_runs'].sum().reset_index()

temp_df1 = delivery[delivery['batsman'] == 'MS Dhoni']
teams_runs1 = temp_df1.groupby('season')['batsman_runs'].sum().reset_index()

trace1 = go.Scatter(x=teams_runs['season'],y=teams_runs['batsman_runs'],mode='lines',text=avg['batsman'],marker={'color':'black','size':15},name='Virat Kohli')
trace2 = go.Scatter(x=teams_runs1['season'],y=teams_runs1['batsman_runs'],mode='lines',text=avg['batsman'],marker={'color':'black','size':15},name='MS Dhoni')

data = [trace1,trace2]
layout = go.Layout(title='Performance against all Teams',xaxis={'title':'Teams'},yaxis={'title':'Runs'})
fig = go.Figure(data=data,layout=layout)

fig.show()

In [30]:
#bar chart

top_10 = list(delivery['batsman'].value_counts().iloc[:10].index)
temp_df = delivery[delivery['batsman'].isin(top_10)]
batsman_runs = temp_df.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).reset_index()
batsman_runs

      batsman  batsman_runs
0    SK Raina          4548
1     V Kohli          4423
2   RG Sharma          4207
3   G Gambhir          4132
4   DA Warner          4014
5  RV Uthappa          3778
6    CH Gayle          3651
7    S Dhawan          3561
8    MS Dhoni          3560
9   AM Rahane          3057

In [31]:

trace1 = go.Bar(x=batsman_runs['batsman'], y=batsman_runs['batsman_runs'])
data = [trace1]
layout = go.Layout(title='Top 10 Batsman Runs',xaxis={'title':'Batsman'},yaxis={'title':'Batsman Runs'})
fig = go.Figure(data=data,layout=layout)
fig.show()

In [ ]:
#two types of bar chart

(1) Overlay bar chart
(2) Stacked bar chart
(3) Sideby Side chart

In [34]:
#bubble chart
top_50 = list(delivery['batsman'].value_counts().iloc[:50].index)

temp_df = delivery[(delivery['batsman'].isin(top_50)) & ((delivery['player_dismissed'] == delivery['batsman']) | (delivery['player_dismissed'] == delivery['non_striker']))]
batsman_out = temp_df.groupby('batsman')['player_dismissed'].count().sort_values(ascending=False)

temp_df0 = delivery[(delivery['batsman'].isin(top_50))]
batsman_runs = temp_df0.groupby('batsman')['batsman_runs'].sum()

temp_df1 = delivery[(delivery['batsman'].isin(top_50)) & (delivery['batsman_runs'] == 6)]
six_number = temp_df1.groupby('batsman')['batsman_runs'].count().reset_index()
six_number.rename(columns = {'batsman_runs':'six'},inplace = True)


avg = (batsman_runs/batsman_out).reset_index()
final_frame = avg.merge(batsman_runs,on='batsman').merge(six_number,on='batsman')


final_frame.rename(columns={0:'Average','batsman_runs':'Runs'},inplace=True)

# avg.head()

In [35]:
final_frame

             batsman    Average  Runs  six
0     AB de Villiers  41.011765  3486  158
1       AC Gilchrist  27.223684  2069   92
2           AJ Finch  27.655172  1604   59
3          AM Rahane  33.593407  3057   60
4          AT Rayudu  27.454545  2416   79
5        BB McCullum  27.550000  2755  124
6           BJ Hodge  30.434783  1400   43
7           CH Gayle  40.566667  3651  266
8          DA Miller  34.733333  1563   78
9          DA Warner  39.352941  4014  160
10          DJ Bravo  23.370370  1262   48
11         DJ Hussey  26.979592  1322   60
12  DPMD Jayawardene  28.250000  1808   40
13          DR Smith  29.444444  2385  117
14      F du Plessis  33.205128  1295   38
15         G Gambhir  31.541985  4132   58
16         IK Pathan  21.698113  1150   38
17         JH Kallis  27.269663  2427   44
18         JP Duminy  41.520833  1993   78
19        KA Pollard  27.694118  2354  148
20     KC Sangakkara  24.449275  1687   27
21        KD Karthik  23.795082  2903   71
22           M Vijay  27.593407  2511   89
23        MEK Hussey  38.019231  1977   52
24         MK Pandey  28.870130  2223   65
25         MK Tiwary  28.413793  1648   39
26          MS Dhoni  33.904762  3560  156
27     Mandeep Singh  19.508772  1112   18
28           NV Ojha  21.273973  1553   79
29          PA Patel  21.700935  2322   35
30          R Dravid  28.233766  2174   28
31         RA Jadeja  22.789474  1732   57
32         RG Sharma  31.162963  4207  173
33        RV Uthappa  28.839695  3778  125
34       S Badrinath  30.020833  1441   28
35          S Dhawan  32.972222  3561   71
36        SC Ganguly  24.981481  1349   42
37          SE Marsh  38.292308  2489   78
38          SK Raina  34.195489  4548  174
39         SPD Smith  34.260000  1713   45
40      SR Tendulkar  32.873239  2334   29
41         SR Watson  30.917647  2628  122
42         SS Tiwary  29.674419  1276   45
43         SV Samson  25.927273  1426   57
44        TM Dilshan  28.121951  1153   24
45           V Kohli  35.103175  4423  160
46          V Sehwag  27.836735  2728  106
47           WP Saha  24.714286  1557   57
48         YK Pathan  29.515152  2922  149
49      Yuvraj Singh  25.910000  2591  141

In [36]:
trace1 = go.Scatter(x=final_frame['Average'], y=final_frame['Runs'],mode='markers',marker={'size':final_frame['six']},text = final_frame['batsman'])
data = [trace1]
layout = go.Layout(title='Batsman Runs',
                   xaxis={'title':'Batsman Average'},
                   yaxis={'title':'Batsman Runs'})
fig = go.Figure(data=data,layout=layout)
fig.show()

In [ ]:
#box plot

# Column shsould be numerical and you will find a distribution of the plot

In [39]:
match_agg = delivery.groupby('match_id')['total_runs'].sum().reset_index()
season_wise = match_agg.merge(match,left_on='match_id',right_on='id')[['match_id','total_runs','season']]
season_wise

     match_id  total_runs  season
0           1         379    2017
1           2         371    2017
2           3         367    2017
3           4         327    2017
4           5         299    2017
..        ...         ...     ...
631       632         277    2016
632       633         317    2016
633       634         302    2016
634       635         325    2016
635       636         408    2016

[636 rows x 3 columns]

In [46]:
trace1 = go.Box(x=season_wise['total_runs'], name='All Season',marker={'color':'#00a65a'})
layout = go.Layout(title='Total Runs Box Plot',
                   xaxis={'title':'Total Score'},
                   )
data = [trace1]
fig = go.Figure(data=data,layout=layout)
fig.show()

In [54]:
trace1 = go.Box(x=season_wise[season_wise['season']==2008], name='2008',marker={'color':'green'})
trace2 = go.Box(x=season_wise[season_wise['season']==2017], name='2017',marker={'color':'blue'})

data = [trace1,trace2]
layout = go.Layout(title='Total Runs Box Plot',
                   xaxis={'title':'Total Score'},
                   )
fig = go.Figure(data=data,layout=layout)
fig.show()

In [ ]:
#dist plot
#combination of three plot histobram,kde,rug plot

In [55]:
import plotly.figure_factory as ff

In [68]:
hist_data = [final_frame['Average'],final_frame['Runs']]
group_label = ['Average','Strikerate']

fig = ff.create_distplot(hist_data,group_label,bin_size=[5,5000])
fig.show()

In [61]:
final_frame

             batsman    Average  Runs  six
0     AB de Villiers  41.011765  3486  158
1       AC Gilchrist  27.223684  2069   92
2           AJ Finch  27.655172  1604   59
3          AM Rahane  33.593407  3057   60
4          AT Rayudu  27.454545  2416   79
5        BB McCullum  27.550000  2755  124
6           BJ Hodge  30.434783  1400   43
7           CH Gayle  40.566667  3651  266
8          DA Miller  34.733333  1563   78
9          DA Warner  39.352941  4014  160
10          DJ Bravo  23.370370  1262   48
11         DJ Hussey  26.979592  1322   60
12  DPMD Jayawardene  28.250000  1808   40
13          DR Smith  29.444444  2385  117
14      F du Plessis  33.205128  1295   38
15         G Gambhir  31.541985  4132   58
16         IK Pathan  21.698113  1150   38
17         JH Kallis  27.269663  2427   44
18         JP Duminy  41.520833  1993   78
19        KA Pollard  27.694118  2354  148
20     KC Sangakkara  24.449275  1687   27
21        KD Karthik  23.795082  2903   71
22           M Vijay  27.593407  2511   89
23        MEK Hussey  38.019231  1977   52
24         MK Pandey  28.870130  2223   65
25         MK Tiwary  28.413793  1648   39
26          MS Dhoni  33.904762  3560  156
27     Mandeep Singh  19.508772  1112   18
28           NV Ojha  21.273973  1553   79
29          PA Patel  21.700935  2322   35
30          R Dravid  28.233766  2174   28
31         RA Jadeja  22.789474  1732   57
32         RG Sharma  31.162963  4207  173
33        RV Uthappa  28.839695  3778  125
34       S Badrinath  30.020833  1441   28
35          S Dhawan  32.972222  3561   71
36        SC Ganguly  24.981481  1349   42
37          SE Marsh  38.292308  2489   78
38          SK Raina  34.195489  4548  174
39         SPD Smith  34.260000  1713   45
40      SR Tendulkar  32.873239  2334   29
41         SR Watson  30.917647  2628  122
42         SS Tiwary  29.674419  1276   45
43         SV Samson  25.927273  1426   57
44        TM Dilshan  28.121951  1153   24
45           V Kohli  35.103175  4423  160
46          V Sehwag  27.836735  2728  106
47           WP Saha  24.714286  1557   57
48         YK Pathan  29.515152  2922  149
49      Yuvraj Singh  25.910000  2591  141

In [ ]:
#histogram

# histogram you just do the frequence count and then add to the graph in a bin as a bar chart

In [77]:
trace= go.Histogram(x=final_frame['Average'],name='Average Variation',xbins={'size':5,'start':30,'end':60})
layout = go.Layout(title='Strikerate Variation of a Batsman',xaxis={'title':'Average'},yaxis={'title':'Frequency'})
data=[trace]
fig = go.Figure(data=data,layout=layout)
fig.show()

In [ ]:
#heatmaps

# both categorical or categorical and Numerical but third column should be numerical

In [80]:
six = delivery[delivery['batsman_runs']==6]
six = six.groupby(['batting_team','over'])['batsman_runs'].count().reset_index()
six.rename(columns={'batsman_runs':'Six'},inplace=True)

In [82]:
dots = delivery[delivery['batsman_runs']==0]
dots = dots.groupby(['batting_team','over'])['batsman_runs'].count().reset_index()
dots.rename(columns={'batsman_runs':'Dots'},inplace=True)
dots

            batting_team  over  Dots
0    Chennai Super Kings     1   524
1    Chennai Super Kings     2   462
2    Chennai Super Kings     3   432
3    Chennai Super Kings     4   421
4    Chennai Super Kings     5   376
..                   ...   ...   ...
275  Sunrisers Hyderabad    16   144
276  Sunrisers Hyderabad    17   157
277  Sunrisers Hyderabad    18   128
278  Sunrisers Hyderabad    19   130
279  Sunrisers Hyderabad    20   117

[280 rows x 3 columns]

In [81]:
trace= go.Heatmap(x=six['batting_team'],y=six['over'],z=six['Six'])
data=[trace]

layout=go.Layout(title='Heat Map',xaxis={'title':'Batting Team'},yaxis={'title':'Six'})

fig=go.Figure(data=data,layout=layout)

fig.show()

In [84]:
trace1= go.Heatmap(x=six['batting_team'],y=six['over'],z=six['Six'])
trace2= go.Heatmap(x=dots['batting_team'],y=dots['over'],z=dots['Dots'])

from plotly import tools
data=[trace1,trace2]

layout=go.Layout(title='Heat Map',xaxis={'title':'Batting Team'})

fig=tools.make_subplots(rows=1,cols=2,subplot_titles=["6's","0's"],shared_yaxes=True)
fig.append_trace(trace1,1,1)
fig.append_trace(trace2,1,2)

fig.show()

/usr/local/lib/python3.11/dist-packages/plotly/tools.py:455: DeprecationWarning:

plotly.tools.make_subplots is deprecated, please use plotly.subplots.make_subplots instead