In [4]:
import requests
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=2e0850db7ea4081bf42cb37c47e14aa2&language=en-US&page=1')

In [8]:
import pandas as pd
df = pd.DataFrame(response.json()['results'])[['id','title','release_date','overview','popularity']]

In [9]:
df.head()

,id,title,release_date,overview,popularity
0,278,The Shawshank Redemption,1994-09-23,Imprisoned in the 1940s for the double murder ...,58.5006
1,238,The Godfather,1972-03-14,"Spanning the years 1945 to 1955, a chronicle o...",33.8222
2,240,The Godfather Part II,1974-12-20,In the continuing saga of the Corleone crime f...,22.0684
3,424,Schindler's List,1993-12-15,The true story of how businessman Oskar Schind...,17.0596
4,389,12 Angry Men,1957-04-10,The defense and the prosecution have rested an...,31.6727

In [13]:
for item in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=2e0850db7ea4081bf42cb37c47e14aa2&language=en-US&page={}'.format(item))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','release_date','overview','popularity']]
    df = pd.concat([df,temp_df])

In [14]:
df.shape

(8580, 5)

In [19]:
df.head(100)

,id,title,release_date,overview,popularity
0,278,The Shawshank Redemption,1994-09-23,Imprisoned in the 1940s for the double murder ...,58.5006
1,238,The Godfather,1972-03-14,"Spanning the years 1945 to 1955, a chronicle o...",33.8222
2,240,The Godfather Part II,1974-12-20,In the continuing saga of the Corleone crime f...,22.0684
3,424,Schindler's List,1993-12-15,The true story of how businessman Oskar Schind...,17.0596
4,389,12 Angry Men,1957-04-10,The defense and the prosecution have rested an...,31.6727
...,...,...,...,...,...
15,18491,Neon Genesis Evangelion: The End of Evangelion,1997-07-19,"SEELE orders an all-out attack on NERV, aiming...",5.3560
16,77338,The Intouchables,2011-11-02,A true story of two men who should never have ...,10.2309
17,28,Apocalypse Now,1979-05-19,"At the height of the Vietnam war, Captain Benj...",7.3638
18,1139087,Once Upon a Studio,2023-09-24,"Created for Disney's 100th anniversary, the sh...",2.4172
19,901,City Lights,1931-02-06,A tramp falls in love with a beautiful blind f...,2.3492

In [20]:
df.to_csv('Movieslist.csv')